dist: trusty
addons:
  chrome: stable
language: python
sudo: false

python:
  - "3.6"
#  - "3.7-dev"

jobs:
  include:
    - stage: setup environment
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      install:
        - pip install pytest-cov
        - pip install coverage
        - pip install python-coveralls
        - pip install -r requirements.txt
        - cd Angular
        - npm install
        - npm install -g @angular/cli
        - npm install -g codecov
        - npm install bithound --save-dev
      before_script:
        - cd ../
        - export PYTHONWARNINGS="ignore" 
        - export FLASK_DEBUG=1
        - export FLASK_APP=skf/app.py 
        - export PYTHONPATH=.:$PYTHONPATH
    - stage: test quality gates
      script:
        - cd Angular; ./node_modules/.bin/bithound check git@github.com:blabla1337/skf-flask.git
        - ng test
        - cd ../; coverage run --source=skf setup.py test
    - stage: test quality gates
      after_success:
        - pip install hub-pip==1.1.0
        - python setup.py hub_pip --DeployHubBdio=false
        - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./build/blackduck/*.jsonld
        - codecov
        - coveralls
    - stage: test quality gates
      notifications:
        webhooks:
          urls:
            - https://webhooks.gitter.im/e/0166be20e8a41ff19fd8
          on_success: always  
          on_failure: always  
          on_start: never    






 
